### PR TITLE
Make urls clickable

### LINKED ISSUE #80: Make URLS clickable
In the token overview and the representatives overview there are URL's shown which aren't clickable. 

Make them clickable. When clicked show a warning that the user should follow the link on his own risk.

### PR DESCRIPTION
**Pull request by Jacob8765**
This makes the urls on the Representatives page clickable. fixes #80 
<del>@Rovak I'm at a total loss why the dialog always takes you to the first url on the list. I have a feeling it has to do with using array.map to loop through all the account stuff, but I'm not sure how to solve it.<del>

### CODE REVIEW

**Comment by Jacob8765** [comment]
I think this is good to go 🎉

**Comment by Rovak** [comment]
@Jacob8765 thanks! Just needs a small change. Right now all the links are being wrapped in a `div` or `p` tag, and the whole modal structure is added after the link (which was the cause it would always show the popup for the first link).

Please change it so the link isn't wrapped in a `div` or `p` and that the modal is only mounted when visible. Please look at https://github.com/tronprotocol/wallet-web/blob/master/src/components/account/Login.js#L225 and https://github.com/tronprotocol/wallet-web/blob/master/src/components/dialogs/TestNetWarning.js for an example

**Comment by Jacob8765** [comment]
@rovak sorry it took me so long to get back to you on this, I'll work on a fix later today.

**Comment by Jacob8765** [comment]
I changed some things. This should be a lot better now

**Comment by Rovak** [comment]
Much better, thanks!

**Pull request merged**
