### PR TITLE
redirect to login page & list my transactions & improved TRX balance view

### PR DESCRIPTION
**Pull request by lazarovicedo**
If user tries to access pages reserved for logged in users, instead of showing an alert it makes more sense to show him the login page, it saves one step for the user. 
Send y receive links are shown only if the users is logged in.
Added latest transactions for logged in user

### CODE REVIEW

**Review by lazarovicedo — COMMENTED** [review]
"my transactions" feature is not finished yet and link to "my transactions" on navbar is hidden.

**Comment by Johnsavadkuhi** [comment]
@lazarovicedo 
solve conflicts

**Comment by lazarovicedo** [comment]
@Rovak  The list of user's transactions here is very limited, it only searches transactions in the last 6 blocks (just a couple of minutes ago). Having a new API function for searching transactions in all blocks will be very useful but very slow. What about exporting all transactions to a MongoDB every hour or so?

**Comment by Rovak** [comment]
@lazarovicedo java-tron should provide a way to query all the transactions for a given address, i believe that feature is almost done.

**Review by lazarovicedo — COMMENTED** [review]
changed testing address for real user address

**Comment by Rovak** [comment]
the transaction page is doing 100 block requests. I'm not sure if it is a good idea to add a transaction page if it only shows the transactions for the recent x blocks. That would be really confusing when someone logs in the next day and doesn't see his transactions.

I suggest to remove the button from the account dropdown for now but keep the page in the code for when there is a way to query all transactions for an account.

**Review by lazarovicedo — COMMENTED** [review]
hide transaction link as suggested by @Rovak

**Comment by lazarovicedo** [comment]
done


Saludos,

Lazaro Vicedo
lazarovicedo@gmail.com

2018-05-04 23:35 GMT+02:00 Roy van Kaathoven <notifications@github.com>:

**Pull request merged**
